# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [master]

jobs:

    ## ---- CI ----
    # Code Stage 
    code-quality:
        uses: ./.github/workflows/code-quality.yml